spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: testDB
model-server:
  url: http://localhost:8081
polygon:
  api:
    baseUrl: https://api.polygon.io/v3
    quotesUrl: /quotes
    indexUrl: /indices
    key: g2jyPjqU2CXRzmdEtLxT864ZCza2FHku
    token: kv5HpUlctjaUWiFTjEalkh_pi3GCJaJS
